script: bundle exec rake
rvm:
  - ree
  - 1.9.3
  - 2.0.0
  - 2.1.0
before_install:
  - gem update --system
  - gem --version
env:
  - RAILS=3.0.20
  - RAILS=3.1.12
  - RAILS=3.2.17
  - RAILS=4.0.3
  - RAILS=4.1.0.rc1
